version: '3.8'

services:
  api:
    container_name: zhongyue-nodejs-api-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./logs:/usr/src/app/logs
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - TZ=UTC
    command: pnpm run start:dev
    env_file:
      - .env
    networks:
      - web_network
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--quiet',
          '--tries=1',
          '--spider',
          'http://localhost:3000/api/health',
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

networks:
  web_network:
    driver: bridge
    external: false
